### ISSUE TITLE
Spring app isn't deploying in TomEE

### ISSUE THREAD

**Issue by rmpestano** [samolisov/spring-vs-ejb-vs-cdi-benchmark#3]
Hi there,

I have tried to deploy the benchmark app into TomEE 1.7.3-plus, cdi and ejb are deployed successfully  but spring is not, I can't access spring endpoint: http://localhost:8080/rest-ws-spring/api/message I got 404.

There is a warning in catalina.out related to spring app:

```
INFO: ------------------------- localhost -> /rest-ws-spring
Jan 31, 2016 5:19:22 PM org.apache.tomee.catalina.TomEEClassLoaderEnricher validateJarFile
WARNING: jar '/home/pestano/servers/apache-tomee-plus-1.7.3/webapps/rest-ws-application/rest-ws-spring/WEB-INF/lib/javax.inject-javax.inject-1.jar' contains offending class: javax.inject.Inject. It will be ignored.
```

And here is benchmark output (see no spring result):

```

# Run complete. Total time: 00:05:57

Benchmark                                        (implementation)    (path)  (port)   (server)   Mode  Samples      Score     Error  Units
p.d.r.b.RestImplementationsBenchmark.messages                 ejb  /message    8080  localhost  thrpt       80  11115.416 ± 277.886  ops/s
p.d.r.b.RestImplementationsBenchmark.messages                 cdi  /message    8080  localhost  thrpt       80  11681.354 ± 205.141  ops/s
pestano@pestano:~/projects/spring-vs-ejb-vs-cdi-benchmark$ 
```

**Comment by rmpestano** [comment]
here is full log:

```
NFO: Server startup in 1032 ms
Jan 31, 2016 7:22:44 PM org.apache.openejb.util.JarExtractor extract
INFO: Extracting jar: /home/pestano/servers/apache-tomee-plus-1.7.3/webapps/rest-ws-application.ear
Jan 31, 2016 7:22:44 PM org.apache.openejb.util.JarExtractor extract
INFO: Extracted path: /home/pestano/servers/apache-tomee-plus-1.7.3/webapps/rest-ws-application
Jan 31, 2016 7:22:44 PM org.apache.openejb.util.JarExtractor extract
INFO: Extracting jar: /home/pestano/servers/apache-tomee-plus-1.7.3/webapps/rest-ws-application/rest-ws-cdi.war
Jan 31, 2016 7:22:44 PM org.apache.openejb.util.JarExtractor extract
INFO: Extracted path: /home/pestano/servers/apache-tomee-plus-1.7.3/webapps/rest-ws-application/rest-ws-cdi
Jan 31, 2016 7:22:44 PM org.apache.openejb.util.JarExtractor extract
INFO: Extracting jar: /home/pestano/servers/apache-tomee-plus-1.7.3/webapps/rest-ws-application/rest-ws-ejb.war
Jan 31, 2016 7:22:44 PM org.apache.openejb.util.JarExtractor extract
INFO: Extracted path: /home/pestano/servers/apache-tomee-plus-1.7.3/webapps/rest-ws-application/rest-ws-ejb
Jan 31, 2016 7:22:44 PM org.apache.openejb.util.JarExtractor extract
INFO: Extracting jar: /home/pestano/servers/apache-tomee-plus-1.7.3/webapps/rest-ws-application/rest-ws-spring.war
Jan 31, 2016 7:22:44 PM org.apache.openejb.util.JarExtractor extract
INFO: Extracted path: /home/pestano/servers/apache-tomee-plus-1.7.3/webapps/rest-ws-application/rest-ws-spring
Jan 31, 2016 7:22:44 PM org.apache.openejb.util.OptionsLog info
INFO: Using 'openejb.deployments.classpath.filter.systemapps=false'
Jan 31, 2016 7:22:44 PM org.apache.openejb.util.OptionsLog info
INFO: Using 'openejb.default.deployment-module=org.apache.openejb.config.WebModule'
Jan 31, 2016 7:22:44 PM org.apache.openejb.util.OptionsLog info
INFO: Using 'openejb.default.deployment-module=org.apache.openejb.config.WebModule'
Jan 31, 2016 7:22:44 PM org.apache.openejb.config.ConfigurationFactory configureApplication
INFO: Configuring enterprise application: /home/pestano/servers/apache-tomee-plus-1.7.3/webapps/rest-ws-application
Jan 31, 2016 7:22:45 PM org.apache.openejb.config.InitEjbDeployments deploy
INFO: Auto-deploying ejb MessageController: EjbDeployment(deployment-id=MessageController)
Jan 31, 2016 7:22:45 PM org.apache.openejb.config.InitEjbDeployments deploy
INFO: Auto-deploying ejb MessageService: EjbDeployment(deployment-id=MessageService)
Jan 31, 2016 7:22:45 PM org.apache.openejb.config.InitEjbDeployments deploy
INFO: Auto-deploying ejb EJBResourceA: EjbDeployment(deployment-id=EJBResourceA)
Jan 31, 2016 7:22:45 PM org.apache.openejb.config.InitEjbDeployments deploy
INFO: Auto-deploying ejb EJBResourceB: EjbDeployment(deployment-id=EJBResourceB)
Jan 31, 2016 7:22:45 PM org.apache.openejb.config.ConfigurationFactory configureService
INFO: Configuring Service(id=Default Managed Container, type=Container, provider-id=Default Managed Container)
Jan 31, 2016 7:22:45 PM org.apache.openejb.config.AutoConfig createContainer
INFO: Auto-creating a container for bean rest-ws-cdi.Comp87748032: Container(type=MANAGED, id=Default Managed Container)
Jan 31, 2016 7:22:45 PM org.apache.openejb.assembler.classic.Assembler createRecipe
INFO: Creating Container(id=Default Managed Container)
Jan 31, 2016 7:22:45 PM org.apache.openejb.core.managed.SimplePassivater init
INFO: Using directory /home/pestano/servers/apache-tomee-plus-1.7.3/temp for stateful session passivation
Jan 31, 2016 7:22:45 PM org.apache.openejb.config.ConfigurationFactory configureService
INFO: Configuring Service(id=Default Singleton Container, type=Container, provider-id=Default Singleton Container)
Jan 31, 2016 7:22:45 PM org.apache.openejb.config.AutoConfig createContainer
INFO: Auto-creating a container for bean MessageController: Container(type=SINGLETON, id=Default Singleton Container)
Jan 31, 2016 7:22:45 PM org.apache.openejb.assembler.classic.Assembler createRecipe
INFO: Creating Container(id=Default Singleton Container)
Jan 31, 2016 7:22:45 PM org.apache.openejb.config.AppInfoBuilder build
INFO: Enterprise application "/home/pestano/servers/apache-tomee-plus-1.7.3/webapps/rest-ws-application" loaded.
Jan 31, 2016 7:22:45 PM org.apache.openejb.assembler.classic.Assembler createAppClassLoader
INFO: Creating dedicated application classloader for rest-ws-application
Jan 31, 2016 7:22:45 PM org.apache.openejb.assembler.classic.Assembler createApplication
INFO: Assembling app: /home/pestano/servers/apache-tomee-plus-1.7.3/webapps/rest-ws-application
Jan 31, 2016 7:22:45 PM org.apache.openejb.cdi.CdiBuilder initSingleton
INFO: Existing thread singleton service in SystemInstance(): org.apache.openejb.cdi.ThreadSingletonServiceImpl@1c72da34
Jan 31, 2016 7:22:45 PM org.apache.openejb.cdi.OpenEJBLifecycle startApplication
INFO: OpenWebBeans Container is starting...
Jan 31, 2016 7:22:45 PM org.apache.webbeans.plugins.PluginLoader startUp
INFO: Adding OpenWebBeansPlugin : [CdiPlugin]
Jan 31, 2016 7:22:45 PM org.apache.webbeans.plugins.PluginLoader startUp
INFO: Adding OpenWebBeansPlugin : [OpenWebBeansJsfPlugin]
Jan 31, 2016 7:22:45 PM org.apache.webbeans.config.BeansDeployer validateInjectionPoints
INFO: All injection points were validated successfully.
Jan 31, 2016 7:22:45 PM org.apache.openejb.cdi.OpenEJBLifecycle startApplication
INFO: OpenWebBeans Container has started, it took 8 ms.
Jan 31, 2016 7:22:45 PM org.apache.tomee.catalina.TomcatWebAppBuilder init
INFO: ------------------------- localhost -> /rest-ws-cdi
Jan 31, 2016 7:22:45 PM org.apache.openejb.cdi.CdiBuilder initSingleton
INFO: Existing thread singleton service in SystemInstance(): org.apache.openejb.cdi.ThreadSingletonServiceImpl@1c72da34
Jan 31, 2016 7:22:45 PM org.apache.openejb.cdi.OpenEJBLifecycle startApplication
INFO: OpenWebBeans Container is starting...
Jan 31, 2016 7:22:45 PM org.apache.webbeans.plugins.PluginLoader startUp
INFO: Adding OpenWebBeansPlugin : [CdiPlugin]
Jan 31, 2016 7:22:45 PM org.apache.webbeans.plugins.PluginLoader startUp
INFO: Adding OpenWebBeansPlugin : [OpenWebBeansJsfPlugin]
Jan 31, 2016 7:22:45 PM org.apache.webbeans.config.BeansDeployer validateInjectionPoints
INFO: All injection points were validated successfully.
Jan 31, 2016 7:22:45 PM org.apache.openejb.cdi.OpenEJBLifecycle startApplication
INFO: OpenWebBeans Container has started, it took 56 ms.
Jan 31, 2016 7:22:45 PM org.apache.openejb.server.cxf.rs.CxfRsHttpListener configureFactory
INFO: Using providers:
Jan 31, 2016 7:22:45 PM org.apache.openejb.server.cxf.rs.CxfRsHttpListener configureFactory
INFO:      org.apache.cxf.jaxrs.provider.JAXBElementProvider@3c07bf87
Jan 31, 2016 7:22:45 PM org.apache.openejb.server.cxf.rs.CxfRsHttpListener configureFactory
INFO:      org.apache.cxf.jaxrs.provider.json.JSONProvider@73dc624
Jan 31, 2016 7:22:45 PM org.apache.openejb.server.cxf.rs.CxfRsHttpListener configureFactory
INFO:      org.apache.openejb.server.cxf.rs.EJBAccessExceptionMapper@487d4f79
Jan 31, 2016 7:22:45 PM org.apache.openejb.server.cxf.rs.CxfRsHttpListener logEndpoints
INFO: REST Application: http://localhost:8080/rest-ws-cdi/api/        -> org.apache.openejb.server.rest.InternalApplication
Jan 31, 2016 7:22:45 PM org.apache.openejb.server.cxf.rs.CxfRsHttpListener logEndpoints
INFO:      Service URI: http://localhost:8080/rest-ws-cdi/api/        -> Pojo psamolysov.demo.restws.controller.MessageController
Jan 31, 2016 7:22:45 PM org.apache.openejb.server.cxf.rs.CxfRsHttpListener logEndpoints
INFO:               GET http://localhost:8080/rest-ws-cdi/api/message ->      String message()
Jan 31, 2016 7:22:45 PM org.apache.tomee.catalina.TomcatWebAppBuilder init
INFO: ------------------------- localhost -> /rest-ws-ejb
Jan 31, 2016 7:22:45 PM org.apache.openejb.assembler.classic.JndiBuilder bind
INFO: Jndi(name=MessageControllerLocalBean) --> Ejb(deployment-id=MessageController)
Jan 31, 2016 7:22:45 PM org.apache.openejb.assembler.classic.JndiBuilder bind
INFO: Jndi(name=global/rest-ws-application/rest-ws-ejb/MessageController!psamolysov.demo.restws.controller.MessageController) --> Ejb(deployment-id=MessageController)
Jan 31, 2016 7:22:45 PM org.apache.openejb.assembler.classic.JndiBuilder bind
INFO: Jndi(name=global/rest-ws-application/rest-ws-ejb/MessageController) --> Ejb(deployment-id=MessageController)
Jan 31, 2016 7:22:45 PM org.apache.openejb.assembler.classic.JndiBuilder bind
INFO: Jndi(name=MessageServiceLocalBean) --> Ejb(deployment-id=MessageService)
Jan 31, 2016 7:22:45 PM org.apache.openejb.assembler.classic.JndiBuilder bind
INFO: Jndi(name=global/rest-ws-application/rest-ws-ejb/MessageService!psamolysov.demo.restws.service.MessageService) --> Ejb(deployment-id=MessageService)
Jan 31, 2016 7:22:45 PM org.apache.openejb.assembler.classic.JndiBuilder bind
INFO: Jndi(name=global/rest-ws-application/rest-ws-ejb/MessageService) --> Ejb(deployment-id=MessageService)
Jan 31, 2016 7:22:45 PM org.apache.openejb.assembler.classic.JndiBuilder bind
INFO: Jndi(name=EJBResourceALocalBean) --> Ejb(deployment-id=EJBResourceA)
Jan 31, 2016 7:22:45 PM org.apache.openejb.assembler.classic.JndiBuilder bind
INFO: Jndi(name=global/rest-ws-application/rest-ws-ejb/EJBResourceA!psamolysov.demo.restws.resource.EJBResourceA) --> Ejb(deployment-id=EJBResourceA)
Jan 31, 2016 7:22:45 PM org.apache.openejb.assembler.classic.JndiBuilder bind
INFO: Jndi(name=global/rest-ws-application/rest-ws-ejb/EJBResourceA) --> Ejb(deployment-id=EJBResourceA)
Jan 31, 2016 7:22:45 PM org.apache.openejb.assembler.classic.JndiBuilder bind
INFO: Jndi(name=EJBResourceBLocalBean) --> Ejb(deployment-id=EJBResourceB)
Jan 31, 2016 7:22:45 PM org.apache.openejb.assembler.classic.JndiBuilder bind
INFO: Jndi(name=global/rest-ws-application/rest-ws-ejb/EJBResourceB!psamolysov.demo.restws.resource.EJBResourceB) --> Ejb(deployment-id=EJBResourceB)
Jan 31, 2016 7:22:45 PM org.apache.openejb.assembler.classic.JndiBuilder bind
INFO: Jndi(name=global/rest-ws-application/rest-ws-ejb/EJBResourceB) --> Ejb(deployment-id=EJBResourceB)
Jan 31, 2016 7:22:45 PM org.apache.openejb.cdi.CdiBuilder initSingleton
INFO: Existing thread singleton service in SystemInstance(): org.apache.openejb.cdi.ThreadSingletonServiceImpl@1c72da34
Jan 31, 2016 7:22:45 PM org.apache.openejb.cdi.OpenEJBLifecycle startApplication
INFO: OpenWebBeans Container is starting...
Jan 31, 2016 7:22:45 PM org.apache.webbeans.plugins.PluginLoader startUp
INFO: Adding OpenWebBeansPlugin : [CdiPlugin]
Jan 31, 2016 7:22:45 PM org.apache.webbeans.plugins.PluginLoader startUp
INFO: Adding OpenWebBeansPlugin : [OpenWebBeansJsfPlugin]
Jan 31, 2016 7:22:45 PM org.apache.webbeans.config.BeansDeployer validateInjectionPoints
INFO: All injection points were validated successfully.
Jan 31, 2016 7:22:45 PM org.apache.openejb.cdi.OpenEJBLifecycle startApplication
INFO: OpenWebBeans Container has started, it took 8 ms.
Jan 31, 2016 7:22:45 PM org.apache.openejb.assembler.classic.Assembler startEjbs
INFO: Created Ejb(deployment-id=EJBResourceB, ejb-name=EJBResourceB, container=Default Stateless Container)
Jan 31, 2016 7:22:45 PM org.apache.openejb.assembler.classic.Assembler startEjbs
INFO: Created Ejb(deployment-id=EJBResourceA, ejb-name=EJBResourceA, container=Default Stateless Container)
Jan 31, 2016 7:22:45 PM org.apache.openejb.assembler.classic.Assembler startEjbs
INFO: Created Ejb(deployment-id=MessageController, ejb-name=MessageController, container=Default Singleton Container)
Jan 31, 2016 7:22:45 PM org.apache.openejb.assembler.classic.Assembler startEjbs
INFO: Created Ejb(deployment-id=MessageService, ejb-name=MessageService, container=Default Singleton Container)
Jan 31, 2016 7:22:45 PM org.apache.openejb.assembler.classic.Assembler startEjbs
INFO: Started Ejb(deployment-id=EJBResourceB, ejb-name=EJBResourceB, container=Default Stateless Container)
Jan 31, 2016 7:22:45 PM org.apache.openejb.assembler.classic.Assembler startEjbs
INFO: Started Ejb(deployment-id=EJBResourceA, ejb-name=EJBResourceA, container=Default Stateless Container)
Jan 31, 2016 7:22:45 PM org.apache.openejb.assembler.classic.Assembler startEjbs
INFO: Started Ejb(deployment-id=MessageController, ejb-name=MessageController, container=Default Singleton Container)
Jan 31, 2016 7:22:45 PM org.apache.openejb.assembler.classic.Assembler startEjbs
INFO: Started Ejb(deployment-id=MessageService, ejb-name=MessageService, container=Default Singleton Container)
Jan 31, 2016 7:22:45 PM org.apache.openejb.server.cxf.rs.CxfRsHttpListener configureFactory
INFO: Using providers:
Jan 31, 2016 7:22:45 PM org.apache.openejb.server.cxf.rs.CxfRsHttpListener configureFactory
INFO:      org.apache.cxf.jaxrs.provider.JAXBElementProvider@641e7df7
Jan 31, 2016 7:22:45 PM org.apache.openejb.server.cxf.rs.CxfRsHttpListener configureFactory
INFO:      org.apache.cxf.jaxrs.provider.json.JSONProvider@12eb6ec9
Jan 31, 2016 7:22:45 PM org.apache.openejb.server.cxf.rs.CxfRsHttpListener configureFactory
INFO:      org.apache.openejb.server.cxf.rs.EJBAccessExceptionMapper@487d4f79
Jan 31, 2016 7:22:45 PM org.apache.openejb.server.cxf.rs.CxfRsHttpListener logEndpoints
INFO: REST Application: http://localhost:8080/rest-ws-ejb/api/        -> org.apache.openejb.server.rest.InternalApplication
Jan 31, 2016 7:22:45 PM org.apache.openejb.server.cxf.rs.CxfRsHttpListener logEndpoints
INFO:      Service URI: http://localhost:8080/rest-ws-ejb/api/        ->  EJB psamolysov.demo.restws.controller.MessageController
Jan 31, 2016 7:22:45 PM org.apache.openejb.server.cxf.rs.CxfRsHttpListener logEndpoints
INFO:               GET http://localhost:8080/rest-ws-ejb/api/message ->      String message()
Jan 31, 2016 7:22:45 PM org.apache.tomee.catalina.TomcatWebAppBuilder init
INFO: ------------------------- localhost -> /rest-ws-spring
Jan 31, 2016 7:22:45 PM org.apache.tomee.catalina.TomEEClassLoaderEnricher validateJarFile
WARNING: jar '/home/pestano/servers/apache-tomee-plus-1.7.3/webapps/rest-ws-application/rest-ws-spring/WEB-INF/lib/javax.inject-javax.inject-1.jar' contains offending class: javax.inject.Inject. It will be ignored.
Jan 31, 2016 7:22:45 PM org.apache.openejb.cdi.CdiBuilder initSingleton
INFO: Existing thread singleton service in SystemInstance(): org.apache.openejb.cdi.ThreadSingletonServiceImpl@1c72da34
Jan 31, 2016 7:22:45 PM org.apache.openejb.cdi.OpenEJBLifecycle startApplication
INFO: OpenWebBeans Container is starting...
Jan 31, 2016 7:22:45 PM org.apache.webbeans.plugins.PluginLoader startUp
INFO: Adding OpenWebBeansPlugin : [CdiPlugin]
Jan 31, 2016 7:22:45 PM org.apache.webbeans.plugins.PluginLoader startUp
INFO: Adding OpenWebBeansPlugin : [OpenWebBeansJsfPlugin]
Jan 31, 2016 7:22:45 PM org.apache.webbeans.config.BeansDeployer validateInjectionPoints
INFO: All injection points were validated successfully.
Jan 31, 2016 7:22:45 PM org.apache.openejb.cdi.OpenEJBLifecycle startApplication
INFO: OpenWebBeans Container has started, it took 7 ms.
Jan 31, 2016 7:22:45 PM org.apache.openejb.assembler.classic.Assembler createApplication
INFO: Deployed Application(path=/home/pestano/servers/apache-tomee-plus-1.7.3/webapps/rest-ws-application)
Jan 31, 2016 7:22:55 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deploying web application directory /home/pestano/servers/apache-tomee-plus-1.7.3/webapps/rest-ws-application
Jan 31, 2016 7:22:55 PM org.apache.tomee.catalina.TomcatWebAppBuilder init
INFO: ------------------------- localhost -> /rest-ws-application
Jan 31, 2016 7:22:56 PM org.apache.openejb.util.OptionsLog info
INFO: Using 'openejb.deployments.classpath.filter.systemapps=false'
Jan 31, 2016 7:22:56 PM org.apache.openejb.util.OptionsLog info
INFO: Using 'openejb.default.deployment-module=org.apache.openejb.config.WebModule'
Jan 31, 2016 7:22:56 PM org.apache.openejb.util.OptionsLog info
INFO: Using 'openejb.default.deployment-module=org.apache.openejb.config.WebModule'
Jan 31, 2016 7:22:56 PM org.apache.openejb.config.ConfigurationFactory configureApplication
INFO: Configuring enterprise application: /home/pestano/servers/apache-tomee-plus-1.7.3/webapps/rest-ws-application
Jan 31, 2016 7:22:56 PM org.apache.openejb.config.InitEjbDeployments deploy
INFO: Auto-deploying ejb MessageController: EjbDeployment(deployment-id=MessageController)
Jan 31, 2016 7:22:56 PM org.apache.openejb.config.InitEjbDeployments deploy
INFO: Auto-deploying ejb MessageService: EjbDeployment(deployment-id=MessageService)
Jan 31, 2016 7:22:56 PM org.apache.openejb.config.InitEjbDeployments deploy
INFO: Auto-deploying ejb EJBResourceB: EjbDeployment(deployment-id=EJBResourceB)
Jan 31, 2016 7:22:56 PM org.apache.openejb.config.InitEjbDeployments deploy
INFO: Auto-deploying ejb EJBResourceA: EjbDeployment(deployment-id=EJBResourceA)
Jan 31, 2016 7:22:56 PM org.apache.openejb.config.AppInfoBuilder build
INFO: Enterprise application "/home/pestano/servers/apache-tomee-plus-1.7.3/webapps/rest-ws-application" loaded.
Jan 31, 2016 7:22:56 PM org.apache.openejb.assembler.classic.Assembler createApplication
INFO: Assembling app: /home/pestano/servers/apache-tomee-plus-1.7.3/webapps/rest-ws-application
Jan 31, 2016 7:22:56 PM org.apache.openejb.assembler.classic.Assembler checkForDuplicates
SEVERE: Application cannot be deployed as it contains deployment-ids which are in use: app: /home/pestano/servers/apache-tomee-plus-1.7.3/webapps/rest-ws-application
Jan 31, 2016 7:22:56 PM org.apache.openejb.assembler.classic.Assembler checkForDuplicates
SEVERE: DeploymentId already used: MessageController
Jan 31, 2016 7:22:56 PM org.apache.openejb.assembler.classic.Assembler checkForDuplicates
SEVERE: DeploymentId already used: MessageService
Jan 31, 2016 7:22:56 PM org.apache.openejb.assembler.classic.Assembler checkForDuplicates
SEVERE: DeploymentId already used: EJBResourceB
Jan 31, 2016 7:22:56 PM org.apache.openejb.assembler.classic.Assembler checkForDuplicates
SEVERE: DeploymentId already used: EJBResourceA
Jan 31, 2016 7:22:56 PM org.apache.tomee.catalina.TomcatWebAppBuilder startInternal
SEVERE: Unable to deploy collapsed ear in war StandardEngine[Catalina].StandardHost[localhost].StandardContext[/rest-ws-application]
org.apache.openejb.DuplicateDeploymentIdException: Application cannot be deployed as it contains deployment-ids which are in use: app: /home/pestano/servers/apache-tomee-plus-1.7.3/webapps/rest-ws-application
    MessageController
    MessageService
    EJBResourceB
    EJBResourceA
	at org.apache.openejb.assembler.classic.Assembler.checkForDuplicates(Assembler.java:1013)
	at org.apache.openejb.assembler.classic.Assembler.createApplication(Assembler.java:701)
	at org.apache.openejb.assembler.classic.Assembler.createApplication(Assembler.java:677)
	at org.apache.tomee.catalina.TomcatWebAppBuilder.startInternal(TomcatWebAppBuilder.java:1261)
	at org.apache.tomee.catalina.TomcatWebAppBuilder.configureStart(TomcatWebAppBuilder.java:1100)
	at org.apache.tomee.catalina.GlobalListenerSupport.lifecycleEvent(GlobalListenerSupport.java:130)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5419)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1263)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1948)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Jan 31, 2016 7:22:56 PM org.apache.catalina.core.ContainerBase removeChild
SEVERE: ContainerBase.removeChild: destroy: 
org.apache.catalina.LifecycleException: An invalid Lifecycle transition was attempted ([before_destroy]) for component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/rest-ws-application]] in state [STARTING_PREP]
	at org.apache.catalina.util.LifecycleBase.invalidTransition(LifecycleBase.java:409)
	at org.apache.catalina.util.LifecycleBase.destroy(LifecycleBase.java:299)
	at org.apache.catalina.core.ContainerBase.removeChild(ContainerBase.java:1040)
	at org.apache.tomee.catalina.TomcatWebAppBuilder.undeploy(TomcatWebAppBuilder.java:1537)
	at org.apache.tomee.catalina.TomcatWebAppBuilder.undeploy(TomcatWebAppBuilder.java:1518)
	at org.apache.tomee.catalina.TomcatWebAppBuilder.startInternal(TomcatWebAppBuilder.java:1267)
	at org.apache.tomee.catalina.TomcatWebAppBuilder.configureStart(TomcatWebAppBuilder.java:1100)
	at org.apache.tomee.catalina.GlobalListenerSupport.lifecycleEvent(GlobalListenerSupport.java:130)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5419)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1263)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1948)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Jan 31, 2016 7:22:56 PM org.apache.catalina.core.ContainerBase addChildInternal
SEVERE: ContainerBase.addChild: start: 
org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/rest-ws-application]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1263)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1948)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.tomee.catalina.TomEERuntimeException: org.apache.openejb.DuplicateDeploymentIdException: Application cannot be deployed as it contains deployment-ids which are in use: app: /home/pestano/servers/apache-tomee-plus-1.7.3/webapps/rest-ws-application
    MessageController
    MessageService
    EJBResourceB
    EJBResourceA
	at org.apache.tomee.catalina.TomcatWebAppBuilder.startInternal(TomcatWebAppBuilder.java:1270)
	at org.apache.tomee.catalina.TomcatWebAppBuilder.configureStart(TomcatWebAppBuilder.java:1100)
	at org.apache.tomee.catalina.GlobalListenerSupport.lifecycleEvent(GlobalListenerSupport.java:130)
	at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5419)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 10 more
Caused by: org.apache.openejb.DuplicateDeploymentIdException: Application cannot be deployed as it contains deployment-ids which are in use: app: /home/pestano/servers/apache-tomee-plus-1.7.3/webapps/rest-ws-application
    MessageController
    MessageService
    EJBResourceB
    EJBResourceA
	at org.apache.openejb.assembler.classic.Assembler.checkForDuplicates(Assembler.java:1013)
	at org.apache.openejb.assembler.classic.Assembler.createApplication(Assembler.java:701)
	at org.apache.openejb.assembler.classic.Assembler.createApplication(Assembler.java:677)
	at org.apache.tomee.catalina.TomcatWebAppBuilder.startInternal(TomcatWebAppBuilder.java:1261)
	... 16 more

Jan 31, 2016 7:22:56 PM org.apache.catalina.startup.HostConfig deployDirectory
SEVERE: Error deploying web application directory /home/pestano/servers/apache-tomee-plus-1.7.3/webapps/rest-ws-application
java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/rest-ws-application]]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:905)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1263)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1948)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Jan 31, 2016 7:22:56 PM org.apache.catalina.startup.HostConfig deployDirectory
INFO: Deployment of web application directory /home/pestano/servers/apache-tomee-plus-1.7.3/webapps/rest-ws-application has finished in 469 ms
```
